AY2122S1-CS2103T-W11-1/tp

.gitignore
docs/_config.yml
docs/_sass/minima/_base.scss
docs/index.md

Update site-wide settings

---

src/main/java/fridgy/logic/commands/ListCommand.java
src/main/java/fridgy/model/ReadOnlyRecipeBook.java
src/main/java/fridgy/model/recipe/Name.java
src/main/java/fridgy/model/recipe/exceptions/RecipeNotFoundException.java
src/main/java/fridgy/storage/JsonSerializableRecipeBook.java

Remove remnants from Person class

---

src/main/java/fridgy/logic/commands/AddCommand.java

Fix add example command

---

src/main/java/fridgy/ui/UiUtil.java

Add spacing to numbered list of steps when viewing recipe

---

docs/DeveloperGuide.md

Edit sections on parsing and logic in Developer's Guide

---

src/main/java/fridgy/model/ingredient/BaseIngredient.java
src/main/java/fridgy/model/ingredient/Ingredient.java
src/test/java/fridgy/model/ingredient/BaseIngredientTest.java
src/test/java/fridgy/model/ingredient/IngredientTest.java
src/test/java/fridgy/testutil/IngredientBuilder.java
src/test/java/fridgy/testutil/TypicalBaseIngredients.java

closes #82 
not integrated w recipe yet
edit: i cmi sorry 😭

base ingredient

---

build.gradle
src/main/java/fridgy/MainApp.java
src/main/java/fridgy/commons/core/LogsCenter.java
src/main/java/fridgy/model/IngredientModel.java
src/main/java/fridgy/model/UserPrefs.java
src/main/java/fridgy/model/util/SampleDataUtil.java
src/main/java/fridgy/storage/InventoryStorage.java
src/main/java/fridgy/storage/JsonInventoryStorage.java
src/main/java/fridgy/storage/JsonRecipeBookStorage.java
src/main/java/fridgy/storage/JsonSerializableInventory.java
src/main/java/fridgy/storage/RecipeBookStorage.java
src/main/java/fridgy/storage/Storage.java
src/main/java/fridgy/storage/StorageManager.java
src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
src/test/java/fridgy/logic/LogicManagerTest.java
src/test/java/fridgy/logic/commands/AddCommandTest.java
src/test/java/fridgy/model/ModelManagerTest.java
src/test/java/fridgy/storage/JsonInventoryStorageTest.java
src/test/java/fridgy/storage/JsonRecipeBookStorageTest.java
src/test/java/fridgy/storage/JsonSerializableInventoryTest.java
src/test/java/fridgy/storage/JsonSerializableRecipeBookTest.java
src/test/java/fridgy/storage/JsonUserPrefsStorageTest.java
src/test/java/fridgy/storage/StorageManagerTest.java
src/test/java/fridgy/testutil/InventoryBuilder.java
src/test/java/fridgy/testutil/RecipeBookBuilder.java

Fix #155 
As now, it is not named addressbook.json, so the sample recipes and ingredients will appear as long as they don't have a `recipebook.json` or `inventory.json`

Remove addressbook traces in code

---

docs/DeveloperGuide.md
docs/index.md

Remove traces of addressbook from docs

---

docs/UserGuide.md
src/main/java/fridgy/commons/core/Messages.java
src/main/java/fridgy/logic/parser/FridgyParser.java
src/test/java/fridgy/logic/commands/recipe/DeleteRecipeCommandTest.java

Minor fixes and UG update for Delete

---

src/main/java/fridgy/ui/RecipeDisplay.java
src/main/java/fridgy/ui/UiUtil.java
src/main/resources/view/Main.css
src/main/resources/view/MainWindow.fxml

Change font size, min window size, adjust steps description padding + truncation

---

src/main/java/fridgy/model/ModelManager.java
src/main/java/fridgy/ui/MainWindow.java
src/main/java/fridgy/ui/TabListPanel.java
src/main/java/fridgy/ui/UiState.java

Fix delete command will shift the selected item and clear command not clearing window when needed
Fix #211

Fix UI behaviour for Delete and Clear commands

---

src/main/java/fridgy/ui/UiState.java

Fix clear bug

---

docs/_sass/minima/custom-styles.scss

Add h1 to custom styles for UG

---

src/main/java/fridgy/storage/recipe/JsonAdaptedRecipe.java
src/test/java/fridgy/storage/recipe/JsonAdaptedRecipeTest.java

Fix optional steps JSON bug

---

src/main/java/fridgy/ui/IngredientListPanel.java
src/main/java/fridgy/ui/RecipeListPanel.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/RecipeDisplay.fxml

fix #223 
And also change javafx fxml to javafx/11 to prevent log spam of javafx version.

Fix log output

---

src/main/java/fridgy/ui/RecipeDisplay.java
src/main/resources/view/Main.css
src/main/resources/view/RecipeDisplay.fxml
src/test/java/fridgy/logic/commands/recipe/DeleteRecipeCommandTest.java

OK I really didn't wanna touch the UI, but the active window cards have been bothering me cos the title is outside of the area.... 
Contain the titles in the cards; it's much more intuitive. Also fixes #229 that pesky UI animation bug

Fix blue line pushing on select card bug, UI improvements for recipe activewindow

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/fridgy/ui/RecipeDisplay.java
src/main/java/fridgy/ui/UiState.java

The message is `This recipe has no step.`

Empty steps UI to display default message

---

src/main/java/fridgy/model/ingredient/Ingredient.java
src/main/java/fridgy/model/recipe/Recipe.java
src/test/java/fridgy/logic/commands/AddCommandTest.java
src/test/java/fridgy/logic/commands/EditCommandTest.java
src/test/java/fridgy/logic/commands/recipe/AddRecipeCommandTest.java
src/test/java/fridgy/logic/commands/recipe/EditRecipeCommandTest.java
src/test/java/fridgy/model/ingredient/IngredientTest.java

Edit comparison to allow for case-insensitive comparison of ingredients and recipes

---

src/main/java/fridgy/logic/parser/ParserUtil.java
src/main/java/fridgy/model/ingredient/Quantity.java
src/main/java/fridgy/model/util/QuantityCalc.java
src/main/java/fridgy/storage/JsonAdaptedIngredient.java
src/main/java/fridgy/storage/recipe/JsonAdaptedIngredient.java
src/main/java/fridgy/ui/IngredientCard.java
src/main/java/fridgy/ui/IngredientDisplay.java
src/test/java/fridgy/model/QuantityCalcTest.java
src/test/java/fridgy/model/ingredient/QuantityTest.java
src/test/java/fridgy/testutil/IngredientUtil.java

Minor changes and bugfixes for Quantity.

---

src/main/java/fridgy/model/ModelManager.java
src/main/java/fridgy/ui/UiState.java

This should fix the bug of cleared item reappearing. And the bug where clear ingredient does not update recipe list.

Fix clear command
